# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Atul Lal
email: atul.lal123@gmail.com
description: > 
  Hello! I am a software developer.
  Always looking to find the most efficient solution.
  Passionate about Distributed Systems, Parallel Computing, and Deep Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://atullal.xyz" # the base hostname & protocol for your site
twitter_username: atulal
github_username:  atullal
# Build settings
markdown: kramdown
